#spring.application.name=demo

# C?u hình k?t n?i MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/myschool_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# KINH NGHI?M TH?C CHI?N: ddl-auto=update
# Spring Boot s? t? ??ng xem code Java c?a b?n có Entity nào và T? ??NG T?O B?NG trong MySQL.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true